### ISSUE TITLE
[FEATURE][APNS] Treat different errors on connection class

### ISSUE THREAD

**Issue by adrianshiokawa** [tq1/node-push-sender#13]
Treat connection class' possible errors
## Tasks
- [x] Log/treat errors for different connection errors
- [ ] Tests
## Definition of Done
- [x] Different connection errors scenarios should be treated
## Reference

[APN Connection Class](https://github.com/argon/node-apn/blob/master/doc/connection.markdown)

**Comment by askmon** [comment]
Tests are blocked by #6
